# Generated by Django 4.0.6 on 2022-11-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simfulloapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='airother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=15)),
                ('dest', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('cur', models.CharField(max_length=15)),
                ('unit', models.CharField(max_length=15)),
                ('rate', models.CharField(max_length=15)),
                ('chargeAt', models.CharField(max_length=15)),
                ('group', models.CharField(max_length=15)),
            ],
        ),
    ]
