# Generated by Django 4.0.6 on 2022-11-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simfulloapp', '0002_airother'),
    ]

    operations = [
        migrations.AddField(
            model_name='lcl',
            name='consol',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
